version: "3.6"

services:
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.6.1
    volumes:
      - "./docker/elasticsearch/data:/usr/share/elasticsearch/data"
    ports:
      - "9200:9200"
      - "9300:9300"
    environment:
      discovery.type: single-node
    ulimits:
      memlock:
        soft: -1
        hard: -1

  postgres:
    image: postgres:9.6.17-alpine
    volumes:
      - "./docker/postgres:/docker-entrypoint-initdb.d"
    ports:
      - "5432:5432"
    environment:
      LANG: en_US.utf8
      POSTGRES_DB: integration
      POSTGRES_USER: user
      POSTGRES_PASSWORD: pass
