version: "3.6"

services:
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.6.1
    volumes:
      - "./docker/elasticsearch/data:/usr/share/elasticsearch/data"
    ports:
      - "9200:9200"
      - "9300:9300"
    environment:
      discovery.type: single-node
    ulimits:
      memlock:
        soft: -1
        hard: -1

